meta_product_name: "Flatify"
meta_title: "Flatify - Share fair"
meta_description: "Manage and keep track of your house expenses with your flatmates"
meta_image: "pizza_sharing.png"
twitter_account: "@product_twitter_account"
